# Site settings
title: "Harry Desmond"
description: 'Senior Research Fellow, Institute of Cosmology and Gravitation, University of Portsmouth'
url: 'https://harrydesmond.github.io'
baseurl: ''
disable_landing_page: true
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Harry Desmond'
  email: harry.desmond@port.ac.uk
  github_username: harrydesmond

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'CLAUDE.md', 'vendor']
