# Site settings
title: "Richard Stiskalek"
description: 'DPhil candidate in Astrophysics at the University of Oxford, Balliol College'
url: 'https://richard-sti.github.io'
baseurl: ''
disable_landing_page: true
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Richard Stiskalek'
  email: richard.stiskalek@physics.ox.ac.uk
  github_username: Richard-Sti
  linkedin_username: richard-stiskalek

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'CLAUDE.md']
